### ISSUE TITLE
Syntax for numbers with units

### ISSUE THREAD

**Issue by Bagolly** [Bagolly/WHISKR-A#10]
### Regarding syntactical changes:
- Case sensititvity?
- Whitespace sensitivity?
- Rules for separation from other tokens? What is considered ***the end*** of a unit?

#### Case 1: Exactly one whitespace
```c#
  string expression = "3 cm";
```
✔️  Easy to validate
❌  Inflexible regarding input
❌  Can be irritating to comform to this rule, especially in longer expressions

#### Case 2: No whitespace
```c#
  string expression = "3cm";
```
✔️  Convenient, easy-to-remember syntax  
❌  Can be tricky to validate due to other formats (like hexadecimal numbers)

#### Case 3: Whitespace insensitive
```c#
   string expression = "3                 cm";
```
✔️ Most flexible regarding input
✔️ Whitespace insensitive like all other types of input
❌ Requires most validation logic most likely

#### Case 1: Case-sensitive; all lowercase
```c#
   string expression = "3 cm";
```
✔️ Easy to remember
✔️ Easy to validate
❌ Inflexible regarding input
❌ Not everyone prefers all lowercase

#### Case 2: Case-sensitive; all uppercase
```c#
  string expression = "3 CM";
```
✔️ Easy to remember
✔️ Easy to validate
❌ Inflexible regarding input
❌ Might be harder to read, especially in longer expressions
❌ Not everyone prefers all uppercase

#### Case 3: Case-insensitive
```c#
  string expression = "3 cM";
```
✔️ Most flexible regarding output
✔️ No need to remember casing
❌ Can cause collisions because casing often matters in units
❌ Requires most code (not by much overall, however)

**Comment by Bagolly** [comment]
Nah too much C++.
For now, it's case sensitive, but one whitespace sounds like the best compromise between readability (and thereby leniency), 
as well as easy parsing.

One potential problem with parsing , is that associating the unit itself with the literal at tokenization time would require for a unit token check after each number parse, even though units are unlikely to be used all that much.
A possible solution is to parse them separately, but then deciding whether it's a variable or a unit for a previous token would add a lot of computation for an 'interpreted' language like WHISKR.

So I will be dropping this feature for now, and consider it an idea to be integrated to the new WHISKR.

**Comment by Mimicicax** [comment]
Noob

**Comment by Bagolly** [comment]
Closed; too open.
