### ISSUE TITLE
BigInteger features

### ISSUE THREAD

**Issue by Mimicicax** [Bagolly/WHISKR-A#9]
BigInteger must support the basic arithmetic operations:

- Addition
- Subtraction
- Multiplication
- Division

Comparisions:

- Equals
- Less than
- Greater than
- Not equal

Bitwise:

- And
- Or
- Not
- Xor
- Left shift
- Right shift

Other operations:
- Powers
- Modulo
- Factorial
 - Absolute value
 - Division with remainder
 - 
IO:

- To string
- Print

Support for other functions (such as `sqrt`, `sin` etc.) is not going to be implemented because these often output decimal numbers, not integers.

BigInteger is immutable (none of the mentioned operations modify the actual object).

**Comment by Bagolly** [comment]
Relational operators will require a significant extension of the grammar and ST handling code. Also, your a fasz.
